"""Emits the standalone public inquiry function into a site build.

This is the mechanism behind the architecture Drake specified:

    private estate operating system
      -> approved-item catalogue export (catalog_manifest.json)
      -> public website (estate/site.py)
      -> secure inquiry endpoint (this module's output, api/inquiry.py)
      -> approved Telegram reviewer (InquiryNotifier chain; a dedicated email
         inbox can be added alongside it later without touching this module)

with the constraint that the public website must never directly access the
private VPS API. ``estate/site.py`` used to point the generated forms at
``{api_base}/estate/inquiry`` on the VPS; they now POST to a same-origin,
relative ``api/inquiry`` path instead, served by the function this module
writes.

The emitted function follows the Vercel Python Serverless Function
convention: any ``api/<name>.py`` exporting a class named ``handler`` that
extends ``http.server.BaseHTTPRequestHandler`` becomes a route at
``/api/<name>``. It is pure standard library — no FastAPI, no third-party
dependency, nothing that needs a requirements.txt beyond what Vercel's
Python runtime already provides — so it can be deployed by copying the site
output directory and nothing else, exactly like the rest of the static site.

``inquiry_validation.py`` and ``inquiry_notifier.py`` are the single source
of truth for validation and delivery logic; this module copies their real,
tested source files into the build output rather than re-implementing them,
so the deployed function and the test suite are always running the same
code.
"""

from __future__ import annotations

import inspect
from pathlib import Path

from estate import inquiry_notifier, inquiry_validation

_HANDLER_SOURCE = '''"""Standalone serverless inquiry endpoint for the Future Only public site.

Generated by estate/serverless.py at build time -- do not hand-edit inside a
built site output directory; edit estate/serverless.py in the repository and
rebuild instead.

This function never talks to the private VPS API. It validates item_id
against catalog_manifest.json (bundled into this same deployment at build
time), rejects items that are sold or otherwise spoken for, discards
honeypot-tripped submissions silently, suppresses duplicate resubmissions,
applies a best-effort per-instance rate limit, and forwards legitimate
inquiries through the InquiryNotifier chain configured by environment
variables (Telegram when configured -- see _lib/inquiry_notifier.py).

What this function can see, and therefore all it can ever leak: the buyer's
own submission, and catalog_manifest.json, which contains nothing but item
IDs and their public status. It has no database handle, no VPS credentials,
no review token, no address, no floor price, and no internal notes. The only
secrets in its environment are the notifier's, and those are never written to
a response, a log line, or an exception message.
"""
from __future__ import annotations

import json
import os
from http.server import BaseHTTPRequestHandler
from pathlib import Path

from ._lib.inquiry_notifier import notifier_from_env
from ._lib.inquiry_validation import (
    MAX_BUNDLE_ITEMS,
    build_audit_record,
    bundle_quote,
    is_duplicate,
    is_item_available,
    is_rate_limited,
    manifest_entries,
    normalize_inquiry,
    parse_basket,
    record_request,
    record_seen,
    validate_bundle,
    validate_inquiry,
)

SITE_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = SITE_ROOT / "catalog_manifest.json"
BUNDLE_CONFIG_PATH = SITE_ROOT / "bundle_config.json"
MAX_BODY_BYTES = 20_000

# Best-effort, per-instance state. A warm Vercel instance keeps these between
# invocations; a cold start or a second concurrent instance starts empty. That
# limit is inherent to a stateless host and is documented rather than hidden:
# it blunts the common single-client abuse case and nothing more. A durable
# limit needs an external store (Vercel KV / Edge Config) or a WAF rule.
_REQUESTS: dict = {}
_SEEN: dict = {}

GENERIC_ERROR = "Invalid request."
UNAVAILABLE_MESSAGE = "Sorry - this piece is no longer available."
BUSY_MESSAGE = "Too many messages just now. Please try again shortly."
THANKS_MESSAGE = "Thank you - we will be in touch."
UNDELIVERED_MESSAGE = (
    "We could not deliver your message just now. Please try again shortly"
    "{email_hint}."
)


def _load_manifest() -> dict:
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        # An unreadable manifest means every item_id fails the membership
        # check, so inquiries about specific items are refused rather than
        # accepted unvalidated. Failing closed is the right direction here.
        return {}


def _load_bundle_config() -> dict:
    """The tier table this build was generated with.

    Written next to the manifest at build time from
    estate/config/pricing.json, so retuning the discounts is a config edit
    plus a rebuild rather than a code change. Unreadable means no tiers,
    which means no discount is ever applied -- failing closed here quotes a
    higher price, never a lower one.
    """
    try:
        data = json.loads(BUNDLE_CONFIG_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"enabled": False, "tiers": [], "round_to": 5,
                "max_items": MAX_BUNDLE_ITEMS}
    if not isinstance(data, dict):
        return {"enabled": False, "tiers": [], "round_to": 5,
                "max_items": MAX_BUNDLE_ITEMS}
    return data


def _undelivered_message() -> str:
    email = (os.environ.get("ESTATE_SELLING_EMAIL") or "").strip()
    return UNDELIVERED_MESSAGE.format(
        email_hint=(" or email " + email) if email else ""
    )


class handler(BaseHTTPRequestHandler):
    def _allowed_origin(self) -> str:
        """The single origin permitted to call this endpoint cross-site.

        Empty (the default) means no CORS header is sent at all, which is
        correct for the real deployment: the form is served from the same
        origin as this function, so it needs no CORS grant. Set
        ESTATE_SITE_ORIGIN only if the catalogue is ever served from a
        different host than the endpoint. The previous wildcard is gone --
        it let any page anywhere post to this endpoint.
        """
        return (os.environ.get("ESTATE_SITE_ORIGIN") or "").strip()

    def _send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        origin = self._allowed_origin()
        if origin:
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Vary", "Origin")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.end_headers()
        self.wfile.write(body)

    def _client_ip(self) -> str:
        forwarded = (self.headers.get("X-Forwarded-For") or "").split(",")[0].strip()
        return forwarded or (self.headers.get("X-Real-IP") or "").strip()

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        origin = self._allowed_origin()
        if origin:
            self.send_header("Access-Control-Allow-Origin", origin)
            self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
            self.send_header("Access-Control-Allow-Headers", "Content-Type")
            self.send_header("Vary", "Origin")
        self.end_headers()

    def do_GET(self) -> None:
        # No readable surface: this endpoint accepts submissions and returns
        # nothing about the catalogue or about prior inquiries.
        self._send_json(405, {"status": "error", "message": GENERIC_ERROR})

    def do_POST(self) -> None:
        try:
            self._handle_post()
        except Exception:  # noqa: BLE001
            # Last-resort guard. A traceback must never reach the buyer, and
            # an exception string here could contain request internals.
            try:
                self._send_json(500, {"status": "error", "message": GENERIC_ERROR})
            except Exception:  # noqa: BLE001
                pass

    def _handle_post(self) -> None:
        try:
            length = int(self.headers.get("Content-Length", 0) or 0)
        except ValueError:
            length = 0
        if length <= 0 or length > MAX_BODY_BYTES:
            self._send_json(400, {"status": "error", "message": GENERIC_ERROR})
            return

        raw = self.rfile.read(length)
        try:
            data = json.loads(raw.decode("utf-8"))
        except (UnicodeDecodeError, ValueError):
            self._send_json(400, {"status": "error", "message": GENERIC_ERROR})
            return
        if not isinstance(data, dict):
            self._send_json(400, {"status": "error", "message": GENERIC_ERROR})
            return

        salt = os.environ.get("ESTATE_INQUIRY_IP_SALT", "")
        client_key = self._client_ip() or "unknown"

        if is_rate_limited(_REQUESTS.get(client_key, [])):
            self._send_json(429, {"status": "error", "message": BUSY_MESSAGE})
            return
        _REQUESTS[client_key] = record_request(_REQUESTS.get(client_key, []))

        manifest = _load_manifest()

        # A basket is untrusted input like everything else in this body. Only
        # well-formed IDs survive parse_basket, only IDs the manifest knows
        # and still lists as available survive validate_bundle, and the
        # prices and bands used to quote it are read out of the manifest --
        # never out of the request. A buyer cannot talk their own basket into
        # a discount.
        basket = parse_basket(data.get("items"))
        is_bundle = bool(basket) or bool(data.get("items"))

        result = validate_inquiry(
            item_id="" if is_bundle else data.get("item_id", ""),
            name=data.get("name", ""),
            contact=data.get("contact", ""),
            message=data.get("message", ""),
            offer=data.get("offer", ""),
            website=data.get("website", ""),
            manifest=manifest,
        )

        if result.is_bot:
            # Silently discard -- do not tell the bot it was caught, and do
            # not forward it to a human.
            self._send_json(200, {"status": "ok", "message": "Thank you."})
            return

        quote = None
        if is_bundle:
            bundle_result = validate_bundle(basket, manifest)
            if not bundle_result.ok:
                status = 409 if bundle_result.unavailable else 400
                self._send_json(
                    status,
                    {
                        "status": "error",
                        "message": "; ".join(bundle_result.errors),
                        # Naming the specific items lets the page grey out
                        # exactly what went, instead of making the buyer
                        # rebuild a basket by trial and error. Every ID here
                        # is one they already hold.
                        "unavailable": sorted(
                            i for i in basket if not is_item_available(i, manifest)
                        ),
                    },
                )
                return
            config = _load_bundle_config()
            quote = bundle_quote(
                manifest_entries(basket, manifest),
                config.get("tiers") or [],
                round_to=int(config.get("round_to", 5) or 0),
            )

        if result.unavailable:
            self._send_json(409, {"status": "error", "message": UNAVAILABLE_MESSAGE})
            return

        if not result.ok:
            self._send_json(400, {"status": "error", "message": "; ".join(result.errors)})
            return

        record = build_audit_record(
            normalize_inquiry(
                item_id="" if is_bundle else data.get("item_id", ""),
                name=data.get("name", ""),
                contact=data.get("contact", ""),
                message=data.get("message", ""),
                offer=data.get("offer", ""),
                quote=quote,
            ),
            client_ip=self._client_ip(),
            user_agent=self.headers.get("User-Agent", ""),
            salt=salt,
        )

        if is_duplicate(record["fingerprint"], _SEEN):
            # Answer as if it worked -- from the buyer's point of view it
            # did, and the reviewer already has the first copy.
            self._send_json(200, {"status": "ok", "message": THANKS_MESSAGE})
            return

        if not notifier_from_env().notify(record):
            # Nothing durable happened. Say so instead of thanking them for a
            # message no human will ever read.
            self._send_json(
                503, {"status": "error", "message": _undelivered_message()}
            )
            return

        record_seen(record["fingerprint"], _SEEN)
        self._send_json(200, {"status": "ok", "message": THANKS_MESSAGE})
'''


def emit_inquiry_function(out_dir: Path) -> None:
    """Write api/inquiry.py plus its copied _lib/ dependencies into out_dir.

    Idempotent and side-effect-free beyond these files: safe to call on
    every build.
    """
    api_dir = Path(out_dir) / "api"
    lib_dir = api_dir / "_lib"
    lib_dir.mkdir(parents=True, exist_ok=True)

    (lib_dir / "__init__.py").write_text("", encoding="utf-8")
    (lib_dir / "inquiry_validation.py").write_text(
        inspect.getsource(inquiry_validation), encoding="utf-8"
    )
    (lib_dir / "inquiry_notifier.py").write_text(
        inspect.getsource(inquiry_notifier), encoding="utf-8"
    )
    (api_dir / "inquiry.py").write_text(_HANDLER_SOURCE, encoding="utf-8")
